export { default as Navbar } from './Navbar';
export { default as Welcome } from './Welcome';
export { default as Services } from './Services';
export { default as About } from './About';
export { default as Team } from './Team';
export { default as Pricing } from './Pricing';
export { default as Blog } from './Blog';
export { default as Contact } from './Contact';
export { default as Copyright } from './Copyright';
